### PR TITLE
[READY TO MERGE] Add some Documentation

### PR DESCRIPTION
**Pull request by Oruss7**
## Add documentation on github.
Updated by contributors (like me)

Bye-bye bukkit.org and the deprecated documentation. 

**Question**: Dev branch is clean to PR on it ?

### CODE REVIEW

**Comment by Oruss7** [comment]
languages file aren't found. Please upload them on github. Let's translator make a PR to add/modify it

**Comment by slipcor** [comment]
the dev branch is waaaay outdated.

I will check this tomorrow - what did you do? you removed a TON of information of former builds, why did you do that?

**Comment by Oruss7** [comment]
I have not finish. A lot of doc is missing. Can you wait 2 days before merge please?
And if possible tell me where are outdated things. Thx

**Comment by slipcor** [comment]
oh sure, I might have to manually merge, but I like what you have added so far :D

so I will possibly at least take what you added, if I don't remove everything

yeah I will take time off for christmas anyways, I will continue developing on monday

**Comment by Oruss7** [comment]
I think  this doc is ready to merge. It's the good old bukkit's doc. I just add configuration file example (I need this every time when I conf an arena).

Thanks

**Comment by Oruss7** [comment]
I'm pretty sure all docs is here :page_facing_up:

**Comment by slipcor** [comment]
merged manually!

**Pull request closed without merging**
